include /etc/nginx/forward.map;


###########################################################################
#                          avisoscatolicos.online                               #
###########################################################################
server {
    listen 443 ssl;
    server_name avisoscatolicos.online;

    ssl_certificate /etc/letsencrypt/live/avisoscatolicos.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/avisoscatolicos.online/privkey.pem;

    resolver 127.0.0.11 valid=30s;

    set $backend http://avisos-catolicos:8006;
    set $front_backend http://avisos-catolicos:4201;


    location ^~ /api {
        access_log /var/log/nginx/root.log combined;
        proxy_pass $backend;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }

    location ~ ^/ {
        access_log /var/log/nginx/root.log combined;
        proxy_pass $front_backend;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }
}


