error_log /dev/stderr;
access_log /dev/stdout;

server {
    listen 80 default_server;
    server_name _;
    server_tokens off;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl default_server;
    server_name _;

    # openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout privkey.pem -out fullchain.pem
    ssl_certificate /app/sites/default/keys/fullchain.pem;
    ssl_certificate_key /app/sites/default/keys/privkey.pem;

    location / {
        root   /app/sites/default/html;
        index  index.html index.htm;
    }

    location /health {
        root   /app/sites/default/html;
        index  health.html;
    }
}