include /etc/nginx/forward.map;
server {
    listen 443 ssl;
    server_name nexus.financeadvisors.com;

    ssl_certificate /etc/letsencrypt/live/nexus.financeadvisors.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nexus.financeadvisors.com/privkey.pem;
 
    client_max_body_size 10G;

    location / {
        proxy_pass http://cicd.liftcl:5000;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_request_buffering off;
        proxy_buffering off;
    }
}
