include /etc/nginx/forward.map;


###########################################################################
#                          qa-api.financeadvisors.com                               #
###########################################################################
server {
    listen 443 ssl;
    server_name qa-api.financeadvisors.com;

    ssl_certificate /etc/letsencrypt/live/qa-api.financeadvisors.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/qa-api.financeadvisors.com/privkey.pem;

    resolver 127.0.0.11 valid=30s;

    set $leadspedia_backend http://qa.app.liftcl:5001;
    set $webhook_listener_service http://qa.app.liftcl:5003;
    set $hubspot_connector http://qa.app.liftcl:5002;
    set $hubspot_mock http://qa.app.liftcl:9001;


    location ^~ /leadspedia/ {
        access_log /var/log/nginx/root.log combined;
        rewrite ^/leadspedia/(.*)$ /$1 break;
        proxy_pass $leadspedia_backend;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }

    location ~ ^/5c-multi-level(/)?$ {
        access_log /var/log/nginx/root.log combined;
        proxy_pass $webhook_listener_service;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }

    location ~ ^/5c-multi-level-local(/)?$ {
        access_log /var/log/nginx/root.log combined;
        proxy_pass $webhook_listener_service;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }

    location ~ ^/hot-transfer(/)?$ {
        access_log /var/log/nginx/root.log combined;
        proxy_pass $webhook_listener_service;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }

    location ~ ^/hot-transfer-local(/)?$ {
        access_log /var/log/nginx/root.log combined;
        proxy_pass $webhook_listener_service;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }
    

    location ~ ^/marketing-postback(/)?$ {
        access_log /var/log/nginx/root.log combined;
        proxy_pass $webhook_listener_service;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }

    location ~ ^/marketing-postback-local(/)?$ {
        access_log /var/log/nginx/root.log combined;
        proxy_pass $webhook_listener_service;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }

    location ~ ^/delete-five9-contact-from-list(/)?$ {
        access_log /var/log/nginx/root.log combined;
        proxy_pass $webhook_listener_service;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }

    location ~ ^/delete-five9-contact-from-list-local(/)?$ {
        access_log /var/log/nginx/root.log combined;
        proxy_pass $webhook_listener_service;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }
}


