include /etc/nginx/forward.map;


server {
    listen 443 ssl;
    server_name qa-matches.financeadvisors.com;

    ssl_certificate /etc/letsencrypt/live/qa-matches.financeadvisors.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/qa-matches.financeadvisors.com/privkey.pem;

    resolver 127.0.0.11 valid=30s;

    set $backend http://qa.app.liftcl:9002;
    set $backend_ws http://qa.app.liftcl:9003;
    set $backend_smartasset http://qa.app.liftcl:5005;
    set $webhook_listener_service http://qa.app.liftcl:5003;

    set $backend_local http://10.255.4.193:9102;
    set $backend_local_ws http://10.255.4.193:9103;


    location / {
        access_log /var/log/nginx/root.log combined;
        proxy_pass $backend;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }

    location ^~ /thirdparty-thankyoupages/ {
        access_log /var/log/nginx/root.log combined;
        rewrite ^/thirdparty-thankyoupages(/.*)$ $1 break;
        proxy_pass $backend_smartasset;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }

    location /ws/ {
        access_log /var/log/nginx/ws.log combined;
        proxy_pass $backend_ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }

    location ~ ^/find-matches(/.+)?/?$ {
        access_log /var/log/nginx/root.log combined;
        rewrite ^/find-matches(/.+)?/?$ /find-matches$1 break;
        proxy_pass $webhook_listener_service;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }


    location ~ ^/find-matches-local(/.+)?/?$ {
        access_log /var/log/nginx/root.log combined;
        rewrite ^/find-matches-local(/.+)?/?$ /find-matches-local$1 break;
        proxy_pass $webhook_listener_service;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }


    location ~ ^/matched-advisors(/.+)?/?$ {
        access_log /var/log/nginx/root.log combined;
        rewrite ^/matched-advisors(/.+)?/?$ /matched-advisors$1 break;
        proxy_pass $webhook_listener_service;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }

    location ~ ^/matched-advisors-local(/.+)?/?$ {
        access_log /var/log/nginx/root.log combined;
        rewrite ^/matched-advisors-local(/.+)?/?$ /matched-advisors-local$1 break;
        proxy_pass $webhook_listener_service;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }

    location ~ ^/wait-for-matches(/.+)?/?$ {
        access_log /var/log/nginx/root.log combined;
        rewrite ^/wait-for-matches(/.+)?/?$ /page/waitForMatches$1 break;
        proxy_pass $backend;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }

    location ~ ^/wait-for-matches-local(/.+)?/?$ {
        access_log /var/log/nginx/root.log combined;
        rewrite ^/wait-for-matches-local(/.+)?/?$ /page/waitForMatches$1 break;
        proxy_pass $backend_local;
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }

    location /ws-local/ {
        access_log /var/log/nginx/ws.log combined;
        proxy_pass $backend_local_ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    	proxy_set_header Forwarded $proxy_add_forwarded;
    }



}

