services:

  inmobiliaria:
    image: ${INMOBILIARIA}
    volumes:
      - ./etc/inmobiliaria:/app/etc
      - ${APPS_WORKSPACE}/inmobiliaria:/app/data
    environment:
      #this is the path inside the container
      - CONFIG_FILE_PATH=/app/etc/config.json
    ports:
      - 127.0.0.1:8005:8005
      - 127.0.0.1:4200:4200
    restart: always
    networks:
      - backend-network

networks:
  backend-network:
    external: true
